### ISSUE TITLE
Sidebar buttons don't work for 15 seconds while the stats load

### ISSUE THREAD

**Issue by ghost** [pi-hole/web#1444]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Upon visiting the web interface, the buttons on the sidebar menu should be immediately navigable (i.e. they should be loaded before anything else). Most of the time, when I open the web interface I want to immediately be able to go to the query log, whitelist, etc., _not_ look at stats.`

**Actual behaviour:**

`The interface spends 15 seconds loading in order to display the stats (so long that Firefox says "A webpage is slowing down your browser"). Meanwhile, the sidebar menu is visible, but clicking the buttons does nothing.`

**Steps to reproduce:**

`Visit the web interface (pi.hole) while logged in. Try clicking the sidebar menu buttons (e.g. "Query Log"). Notice how they don't work until the stats have been loaded.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/l3h3igckjc`

**Comment by XhmikosR** [comment]
Should be fixed in 5.1.0, can you try the devel branch?

**Comment by ghost** [comment]
I switched to the devel branch, and the first few times I visited the dashboard, it loaded quickly and I think the sidebar buttons would work even while loading.
After a few refreshes, it got worse. The dashboard started to spend just over 60 seconds loading, much slower than before. And, like before, the sidebar buttons wouldn't work while it was loading. Clearing cache & cookies didn't help.
I switched back to the master branch and now I'm back to 15 second loading times.

I might add that the loading times I am describing are not estimates. Every time I tested, it **consistently** takes just over 60 seconds for the dev version to load, and just over 15 seconds for the stable version.

Such problems do not occur while logged out of the web interface, with the limited statistics display.

**Comment by XhmikosR** [comment]
What's your browser version and device you are using to view the dashboard?

Do note that every time you switch branches you need to clear your browser's cache (there's a PR in core to fix that, but hasn't landed yet)

Other things to try:

1. use another browser and/or device and see if the issue happens
2. backup your db, and increase the privacy levels so that less stuff are logged
3. if you have time, you could give the `adminlte-3` branch a go but at this point I doubt it would help you, but it might be worth a try

I'm not sure what info the other devs have access on tricorder, so I'm trying to pinpoint the issue.

We don't have a `setTimeout` every 60 seconds AFAICT, so something else must be going on.

**Comment by ghost** [comment]
I was testing with Firefox on Windows.

Chrome on Windows takes ~40 seconds

Safari on iOS takes ~25 seconds

**Comment by ghost** [comment]
Ok... I haven’t changed anything, but now it’s not happening anymore, on any browser or device.

That is - the dashboard isn’t taking so long to load anymore. I do still have the same gripe that the menu buttons don’t work while the dashboard loads (momentarily).
